kind: Namespace
apiVersion: v1
metadata:
   name: demo1
   labels:
      app: demo1
---
apiVersion: v1
kind: Service
metadata:
   name: demo1-lb
   namespace: demo1
   labels:
      app: demo1
spec:
   type: LoadBalancer
   ports:
      - protocol: TCP
        port: 3000
        nodePort: 30300
        targetPort: 80
   selector:
      app: demo1
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deploy
  namespace: demo1
  labels:
    app: demo1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
